name: Build, Test and Deploy to AKS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RESOURCE_GROUP: python-rg
  CLUSTER_NAME: python-app-cluster
  ACR_NAME: pythonacrap
  APP_NAME: python-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate Dockerfile exists
      run: |
        if [ ! -f Dockerfile ]; then
          echo "::error::Dockerfile not found in repository root"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your test command here
        pytest tests/  # Example test command

  deploy-to-aks:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push image to ACR
      run: |
        az acr build --registry $ACR_NAME \
                     --image $APP_NAME:${{ github.sha }} \
                     --file Dockerfile .

    - name: Verify ACR image exists
      run: |
        az acr repository show-tags --name $ACR_NAME --repository $APP_NAME --output table

    - name: Get AKS credentials
      run: |
        az aks get-credentials --name $CLUSTER_NAME \
                               --resource-group $RESOURCE_GROUP \
                               --overwrite-existing

    - name: Deploy to AKS
      run: |
        # Check if deployment exists
        if kubectl get deployment/$APP_NAME; then
          # Update existing deployment
          kubectl set image deployment/$APP_NAME \
            $APP_NAME=$ACR_NAME.azurecr.io/$APP_NAME:${{ github.sha }} \
            --record
        else
          # Create new deployment if it doesn't exist
          kubectl create deployment $APP_NAME \
            --image=$ACR_NAME.azurecr.io/$APP_NAME:${{ github.sha }}
          kubectl expose deployment $APP_NAME \
            --type=LoadBalancer \
            --port=80 \
            --target-port=5000
        fi
        
        # Wait for rollout to complete
        kubectl rollout status deployment/$APP_NAME
        kubectl get services -w
